name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: |
            echo "Multi-line Shell Commands"
            echo "First step"
            echo "Second step"
      - name: Print goodbye
        run: echo "Done - bye!"
